### ISSUE TITLE
Deserialization does not support `init=False` fields

### ISSUE THREAD

**Issue by a-gardner1** [pengyunie/seutil#30]
Thanks for making this package available; I've found the `io` and `bash` subpackages to be particularly convenient. 
However, a `TypeError` is encountered when trying to [deserialize dataclasses](https://github.com/pengyunie/seutil/blob/53594af5ff145d58c24f598c98f27d3b4278c88f/seutil/io.py#L576) with `init=False` fields because the constructor does not expect the additional keyword argument.

```python
>>> @dataclass
... class Test:
...     a : int
...     b : int = field(init=False)
...     def __post_init__(self):
...         self.b = 2 * self.a
... 
>>> data = io.serialize(Test(2))
>>> data
{'a': 2, 'b': 4}
>>> io.deserialize(data, Test)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.8/site-packages/seutil/io.py", line 579, in deserialize
    return clz(**field_values)
TypeError: __init__() got an unexpected keyword argument 'b'
```

I suggest the following (untested) fix for the linked section of code:

```python
    if dataclasses.is_dataclass(clz):
        init_field_values = {}
        non_init_field_values = {}
        for f in dataclasses.fields(clz):
            if f.name in data:
                field_values = init_field_values if f.init else non_init_field_values
                field_values[f.name] = deserialize(
                    data.get(f.name), f.type, error=error
                )
        obj = clz(**init_field_values)
        for f_name, f_value in non_init_field_values:
            # use object.__setattr__ in case clz is frozen
            object.__setattr__(obj, f_name, f_value)
```

**Comment by pengyunie** [comment]
Thanks for figuring out the issue. I knew the support for dataclass is somewhat incomplete when I wrote this part of code, but I don't have the need to use features like `init=False` and thus wasn't much motivated to complete it. Help welcomed here.

As for the fixes (for this one and #31), I'll be happy to accept as long as they don't break existing test cases.

`for f_name, f_value in non_init_field_values:` -> `for f_name, f_value in non_init_field_values.items():`
