### ISSUE TITLE
su.bash.run timeout does not kill the process when stdout or stderr is redirected

### ISSUE THREAD

**Issue by CptGit** [pengyunie/seutil#67]
The process in `su.bash.run` was not killed if its stdout or stderr is redirected, for example:

Script `z` that needs at least 5 seconds to finish
```bash
#!/bin/bash
echo >z.txt                                                                                                                                       
sleep 5
echo "done" >>z.txt
```

`su.bash.run(cmd='./z >a.txt', timeout=1)`, `su.bash.run(cmd='./z 2>&1', timeout=1)` does not kill the process after timeout.
However `su.bash.run(cmd='./z', timeout=1)` does kill the process.

**Comment by pengyunie** [comment]
cannot reproduce, try if this test passes on your side: https://github.com/pengyunie/seutil/blob/67-subashrun-timeout-does-not-kill-the-process-when-stdout-or-stderr-is-redirected/tests/test_bash.py#L40

**Comment by CptGit** [comment]
The test oracle does not work, TimeOutExpired is always raised.
Check if `z.txt` contains "done"; if it is killed, then it should not.
